### ISSUE TITLE
Missing shcIpAddress field

### ISSUE THREAD

**Issue by shllg** [BoschSmartHome/bosch-shc-api-docs#59]
Hello dear Bosch-Team,

after getting awesome support and debugging an application using your API, we found that with the version switch (I guess from `2.5` to `2.6`) the field `shcIpAddress` has been removed from the API call to `https://x.x.x.x:8446/smarthome/public/information --no-check-certificate`. Since the integration relies on that field, my home automation with all my Bosch products is broken now.

The Bosch mobile application itself has a field which is called "IP-Adresse des Smart Home Controllers". This field is always empty. So I guess the app is expecting that field in the same way.

Can you provide some more information? Is the removal for purpose or will we see the field again inside responses?

https://github.com/tschamm/boschshc-hass/issues/42

**Comment by sebastianharder** [comment]
Hi @shllg,

we did **not** remove the `shcIpAddress` field, but it is omitted if the IP address could not be determined.

Since the mobile app has different ways to determine the IP address (mDNS, manual entry), the empty field under "More" > "System" > "Smart Home Controller" is not necessarily related.

I suggest to contact the customer support and upload your system protocol for further analysis why the IP address cannot be determined on your Smart Home Controller: https://www.bosch-smarthome.com/de/de/service/serviceangebote/kontakt/

Cheers, Sebastian

**Comment by shllg** [comment]
Hi @sebastianharder 
thank you for the fast response. I opened a ticket and waiting for response.

**Comment by sebastianharder** [comment]
We made some code changes determining the local IP address, which will hopefully fix this issue. The changes will be part of the 10.6 SHC update.

**Comment by shllg** [comment]
Just a little update here. With the last version, the IP address is communicated again 👍
