### ISSUE TITLE
Micromodule Relay Impulse Switch

### ISSUE THREAD

**Issue by tschamm** [BoschSmartHome/bosch-shc-api-docs#88]
I'm struggeling with the API of the `ImpulseSwitch` service. As it is just sending an impulse, it cannot be a switch but has to act as a button. Can you provide details how to trigger the impulse via the API? I guess it can be either via PUT the state to `True`, or does it have a separate POST call like when triggering a scenario?

The issue relates to https://github.com/tschamm/boschshc-hass/issues/101

**Comment by sebastianharder** [comment]
@tschamm, the relay configured as ImpulseSwitch is hard to map as a normal switch, because you cannot read the actual state of the connected device. That's why we also cannot support the relay in HomeKit when configured as ImpulseSwitch.

To send an impulse, it should be fine to post to `/devices/{relayId}/ImpulseSwitch` with `impulseState` set to `true`.

API documentation is lacking this information still. We will update this.
